### ISSUE TITLE
Unknown tag 'jsfiddle' 

### ISSUE THREAD

**Issue by rexdf** [octopress/octopress#101]
```bash
Liquid Exception: Unknown tag 'jsfiddle' in _posts/2013-10-23-octopress-dai-ma-gao-liang.mdown
jekyll 2.5.3 | Error:  Unknown tag 'jsfiddle'
```

Should I just remove the jsfiddle or is there a plugin for it?

**Comment by imathis** [comment]
There is no jsfiddle plugin any more. You can port the one you used to use from imathis/octopress or you can remove it if you're not using it.
