### ISSUE TITLE
{{ date }} not working on "new page" command

### ISSUE THREAD

**Issue by dwhoban** [octopress/octopress#103]
I have installed the gem then executed octopress new PATH to create the site.

I have added "date: {{ date }}" to the page template in _templates as per the Readme, essentially replicating the posts template.

However when I execute the command to create a new page this does not work and simply produces a blank field.  

{{ YMD }} seems to work, however produces a date is the MM/DD/YY format.

Problem exists on both Windows 7 and OS X Yosemite.

**Comment by imathis** [comment]
I'm sorry for letting this issue sit for so long. I somehow missed it until now. It should be fixed now as I've released version 3.0.7. Thanks for posting this!

**Comment by dwhoban** [comment]
Thanks Brandon,

Let me know how I can contribute to the docs too.
