### ISSUE TITLE
Version conflict with GitHub pages

### ISSUE THREAD

**Issue by hseeberger** [octopress/octopress#105]
```
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    github-pages (= 33) ruby depends on
      jekyll (= 2.4.0) ruby

    octopress-video-tag (>= 0) ruby depends on
      jekyll (~> 2.0) ruby

    octopress-video-tag (>= 0) ruby depends on
      jekyll (~> 2.0) ruby

    octopress-video-tag (>= 0) ruby depends on
      jekyll (~> 2.0) ruby

    octopress-image-tag (>= 0) ruby depends on
      jekyll (>= 0) ruby

    octopress-video-tag (>= 0) ruby depends on
      jekyll (~> 2.0) ruby

    octopress (>= 0) ruby depends on
      jekyll (~> 2.5) ruby
```

**Comment by imathis** [comment]
This is definitely a problem caused by the strictness of the GitHub pages gem. @parkr, What do you recommend here?

**Comment by parkr** [comment]
I'd probably do >= 2.0 wherever it's possible but you may not yet support 3.0 :(

**Comment by hseeberger** [comment]
@imathis, any chance to get this fixed soon?

**Comment by imathis** [comment]
Octopress relies on features from Jekyll 2.5, but I've found a way around that and been able get the Octopress CLI working with Jekyll 2.4. I can release a version that you can use, but Octopress Ink and other plugins rely on features from Jekyll 2.5, so depending on what you use, you may still have the conflict.

Also, when 3.0 is released, everything will begin to require 3.0. I hope that GitHub Pages will be able to move to 3.0 quickly, but it may be a little while before you can use the newer versions of things.

**Comment by hseeberger** [comment]
Thanks for the quick reply, very much appreciated!

I'm using these Octopress gems:

```
group :jekyll_plugins do
  gem 'octopress'
  gem 'octopress-genesis-theme'
  gem 'octopress-image-tag'
  gem 'octopress-video-tag'
  gem 'octopress-codefence'
end
```

Would the workaround work for these? If so, please let me know when/how to access the release.

**Comment by imathis** [comment]
I'm finishing it up right now. Octopress Ink (which the Genesis Theme relies on) will be the tricky part. I think I can get it to work though.

**Comment by hseeberger** [comment]
Sounds good ;-)

**Comment by parkr** [comment]
Yay @imathis!
