### ISSUE TITLE
Bug: Flag -d on new post will never add a custom date

### ISSUE THREAD

**Issue by moritzheiber** [octopress/octopress#106]
The flag `-d` it duplicated in [lib/octopress/commands/new.rb](https://github.com/octopress/octopress/blob/master/lib/octopress/commands/new.rb#L43) due to `-d` [also being an option for `add_page_options`](https://github.com/octopress/octopress/blob/master/lib/octopress/commands/helpers.rb#L6). Thus it's never possible to add a custom date to a new post.

A solution would be to rename or to remove the shortcode for either one of them.

**Comment by imathis** [comment]
Good catch. I've released 3.0.4 to address this. Thanks!
