### ISSUE TITLE
Theme management

### ISSUE THREAD

**Issue by pavelloz** [octopress/octopress#108]
Hi,

I didnt find any info about that matter besides one [question on SO](http://stackoverflow.com/questions/15421831/is-it-necessary-advisable-to-remove-the-default-theme-in-octopress-when-installi).

I would suppose that it is very common use case for many people:
* Install octopress
* Install theme, find out that its outdated, install another one, another one -- found my perfect match
* commit & deploy

And here I am now. Fortunately i only tried one theme but still there is a lot of unused files in my `sass`, `source/*` directories that i dont want. The problem is now i need to look at what has been there before, manually remove files from old theme and hope for the best. Im after 2 hard git resets and frankly im getting a little bit bored by this process. 

Is there any way of easily putting every theme files into their respective directories and just put the directory name into `_config.yml` to help engine find those files? I just cant believe it has to be this bad, slapping files all over the place without even taking into consideration anything that was there before. Maybe old theme should be just copied to `_oldtheme` or something. You guys are smart, i know you will find out the best way for everybody.

Otherwise i found octopress and jekyll in general very user friendly and well documented projects, so good job guys.

Regards,
Pawel

**Comment by plttn** [comment]
@pavelloz I know @imathis can explain this far better than I can, but the short version is themes were never intended to be installed like how themes are installed on 2.0. 3.0 has a much better way of supporting themes (so I've heard anyways).

**Comment by gntech** [comment]
check out brandon's talk at jekyllconf where he explains about the new theme handling in octopress 3.0. It is based on something called octopress-ink

**Comment by imathis** [comment]
From [the latest post on octopress.org](http://octopress.org/2015/01/15/octopress-3.0-is-coming/)

> Then there are the themes. I planned to create a system for distributing themes independently from Octopress, but I hadn’t solved it when I released 2.0. Even then, I've come across quite a few websites with Octopress theme galleries. While there are some nice ones, they are all distributed through git and installed with an ill-conceived rake task that was never meant to be used for this. All of this is a constant reminder that many people are spending time building on my mistakes.

Octopress is changing. Version 3 is already out there, but I'm still working on themes, so I can kill off version 2. I'm happy to continue discussion here, but since this is more of a question than an issue, I'm going to close it.

**Comment by pavelloz** [comment]
Thank you all for such a quick response.
I didn't know that 3.0 is coming, I should pay more attention to the project blog before asking :)
