### ISSUE TITLE
Deploy results in "unknown file type" error 

### ISSUE THREAD

**Issue by john-goldsmith** [octopress/octopress#109]
First off: thanks for all of your hard work making Octopress :+1:

After generating a new site using v3.0.6 and configuring deployment using Git, running `octopress deploy` results in the following error:

`octopress 3.0.6 | Error:  unknown file type: /Users/jgoldsmith/Sites/blog-octopress/_site/.`

Manually creating a `_site` directory solves the issue, but the only thing that's pushed to my `master` branch is any empty `.deploy` directory as seen [here](https://github.com/john-goldsmith/blog-octopress).  Am I missing something along the way or are components of 3.0 still in flight?

**Comment by imathis** [comment]
Sorry to take a while to get back to you on this John. What is your Jekyll configured destination directory?  Is Jekyll building to `_site`? Are you running the deploy command from the root of your project?

**Comment by imathis** [comment]
@john-goldsmith I'd love to help you if you can answer some of these questions ^ :)

**Comment by elboulangero** [comment]
Hi, I stumbled on the same problem while trying to get started with octopress. This error shows up when the `_site` directory doesn't exist (btw, you miss a check in your code, in  ). And in my case, '_site' doesn't exist because I never built

**Comment by imathis** [comment]
Oh I should have posted. A new version of octopress-deploy has been released. It checks for the presence of the `_site` directory and aborts with a helpful message if you haven't built yet. I think that solves this issue.
