### ISSUE TITLE
Update README to include deploy info

### ISSUE THREAD

**Issue by john-goldsmith** [octopress/octopress#110]
As part of the new user onboarding process, I'd encourage you to update the README to either include or link to the [deploy docs](https://github.com/octopress/deploy), especially in light of the migration from 2.0 to 3.0.  Since `octopress-deploy` is a [core dependency](https://github.com/octopress/octopress/blob/master/octopress.gemspec#L24), there's immediately a discrepancy between the README and running `octopress --help`, the latter of which yields a `deploy` command.  This in turn requires a user to run `octopress deploy --help` (which isn't all that helpful), `octopress docs`, or figure out that there's a completely separate repo that handles this functionality.

**Comment by imathis** [comment]
Good call. Thanks for posting this!
