### ISSUE TITLE
Implement preview functionality

### ISSUE THREAD

**Issue by lunaskyrise** [octopress/octopress#112]
The ```rake preview``` functionality seems to be gone from Octopress 3, leaving one unable to test the resulting site without resorting to a full deployment via e.g. rsync to a test VM.

Can this functionality be reimplemented?

**Comment by plttn** [comment]
Preview/generate is now under the purview of jekyll, so you'd want `jekyll serve`.

**Comment by imathis** [comment]
That's correct, Octopress no longer uses Rake and it no longer offers features that Jekyll offers. You can read the full CLI docs on the README for this project. Thanks for the assist @plttn!
