### ISSUE TITLE
css/main.scss is executable

### ISSUE THREAD

**Issue by oblitum** [octopress/octopress#117]
Just got back to Octopress, now 3.0 =).

I've just generated a scaffold site and noticed in Vim that `css/main.scss` is with executable permission, which is weird.

Regards!

**Comment by imathis** [comment]
Where has this main.scss file come from? Why do you expect that Octopress has something to do with this?

**Comment by oblitum** [comment]
Well, I don't know, I just generated the scaffold site as stated in the docs, if octopress has nothing to do with this file sorry, the culprit should be elsewhere then, but I dunno from where the default scaffold site files comes from.

**Comment by imathis** [comment]
Ah, that comes from Jekyll's site scaffold. Octopress adds the `_templates` directory, and the rest comes from Jekyll. How strange that it's executable. You may want to file an issue on Jekyll.

**Comment by oblitum** [comment]
Ah!!!, Nevermind, I just recalled that I've generated the default jekyll site before running octopress (force init) over the same directory. I believe it was this, if I recall correctly.

**Comment by oblitum** [comment]
Ok, no problem.
