### ISSUE TITLE
#call(<DirectoryWatcher::Event type: removed path: 'source/robots.txt'>) and all I got was this lousy exception Build Failed

### ISSUE THREAD

**Issue by e9t** [octopress/octopress#124]
My build fails when I run `rake preview`.

<pre>
...
/Library/Ruby/Gems/2.0.0/gems/directory_watcher-1.5.1/lib/directory_watcher/threaded.rb:258:in `do_work'
/Library/Ruby/Gems/2.0.0/gems/directory_watcher-1.5.1/lib/directory_watcher/threaded.rb:231:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/directory_watcher-1.5.1/lib/directory_watcher/threaded.rb:228:in `loop'
/Library/Ruby/Gems/2.0.0/gems/directory_watcher-1.5.1/lib/directory_watcher/threaded.rb:228:in `run'
/Library/Ruby/Gems/2.0.0/gems/directory_watcher-1.5.1/lib/directory_watcher/threaded.rb:218:in `block in start'
Build Failed
Called #<Proc:0x007fb3dc01ed10@/Library/Ruby/Gems/2.0.0/gems/jekyll-0.12.1/bin/jekyll:250>#call(<DirectoryWatcher::Event type: added path: 'source/robots.txt'>) and all I got was this lousy exception Build Failed
[2015-07-15 20:59:18] regeneration: 1 files changed
</pre>

This happens not only for 'source/robots.txt', but also for 'source/index.html', 'source/CNAME' and 'source/atom.xml'. Sometimes it says it 'added path' as the error message above, and some other times its says 'removed path'.

It seems only autogenerating during `rake preview` fails, because if I `rake generate` first, then `rake preview`, I can see my changes applied.

I'm not sure if this is related, but I've just upgraded from Octopress 2.0 to 3.0.4.

**Comment by justinrummel** [comment]
You now use the jekyll command to preview and build.  Think of Octopress as a helper to Jekyll vs. a standalone application.  

I wrote my findings about six months ago here: https://www.justinrummel.com/migrating-from-octopress-2-to-octopress-3/

**Comment by e9t** [comment]
Thanks Justin!
I'm afraid I wasn't aware of the updated commands. I'm getting other errors with jekyll now, but since the problem I mentioned in this issue is no longer a problem, I'll close this issue.
