### ISSUE TITLE
Any reason for octopress unpublish to rename filename based on post title?

### ISSUE THREAD

**Issue by oblitum** [octopress/octopress#126]
I've just done my first `octopress unpublish` on a post and it did an unexpected thing, it moved the post file from `_posts` to `_drafts` but, it has renamed the file based on the current title of the post, this is really unwanted for me since I've purposely reworded the title a bit to not be the same as its filename version.

**Comment by imathis** [comment]
Good call. I shouldn't change the file slug. I'll work up a fix for that.

**Comment by oblitum** [comment]
Cool, thanks!

**Comment by imathis** [comment]
Alright. I've just released 3.0.11 which should address this. Tanks for posting the issue!
