### ISSUE TITLE
Using `ß` in Templates causes invalid byte sequence error

### ISSUE THREAD

**Issue by suchja** [octopress/octopress#131]
I'm getting the `Error:  invalid byte sequence in US-ASCII` when using the `#` as part of a template. I found jekyll/jekyll#960 and tried using utf-8 in _config.yml without any success. Guess this shouldn't be the problem as I'm running Jekyll in Version 2.5.3 with ruby 2.1.6p336.

I get the below error when trying to create a new post with octopress in version 3.0.0.rc.33. Any suggestions? Not sure whether this is an octopress issue or an jekyll issue. The used Template for post is also shown below.

```
> octopress new post "Dateien erstellen" --dir c-programmieren --trace
/usr/local/bundle/gems/octopress-3.0.0.rc.33/lib/octopress/page.rb:176:in `parse_template': invalid byte sequence in US-ASCII (ArgumentError)
	from /usr/local/bundle/gems/octopress-3.0.0.rc.33/lib/octopress/page.rb:135:in `content'
	from /usr/local/bundle/gems/octopress-3.0.0.rc.33/lib/octopress/page.rb:30:in `initialize'
	from /usr/local/bundle/gems/octopress-3.0.0.rc.33/lib/octopress/commands/new.rb:52:in `new'
	from /usr/local/bundle/gems/octopress-3.0.0.rc.33/lib/octopress/commands/new.rb:52:in `block (3 levels) in init_with_program'
	from /usr/local/bundle/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /usr/local/bundle/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/octopress-3.0.0.rc.33/bin/octopress:16:in `<top (required)>'
	from /usr/local/bundle/bin/octopress:16:in `load'
	from /usr/local/bundle/bin/octopress:16:in `<main>
```

Here the content of _drafts/post file:
```
---
layout: {{ layout }}
title: {{ title }}
excerpt:
categories: {{ dir }}
lernmoment: {{ dir }}
tags: []
image:
  feature: {{ dir }}.jpg
modified:
---


Jetzt viel Spaß mit

Jan

### Merke

-	

### LernQuiz

Verwende folgende Fragen um das gelernte von heute zu festigen:

-	

### Weitere Informationen
```

**Comment by tooh** [comment]
Perhaps this helps
export LANG=en_US.utf-8 :)

**Comment by suchja** [comment]
@tooh Just tried it, but the problem remains.

I just realised that the problem isn't the `#`. Instead I'm using an `ß` in one of my sentences. This seems to cause the trouble. I had a look for "Umlaute", but missed the `ß`. Sorry for this confusion!

**Comment by imathis** [comment]
This is usually because of editor or shell encoding not being set to utf-8. I assume your editor is writing ASCII to the template and that's causing the error.

**Comment by imathis** [comment]
This really is something that should be solved in the shell or the editor, but I'm trying something to see if I can force the template to UTF-8. If you're using a Gemfile for your site, update it to `gem 'octopress', '3.0.12.pre.1'` or if you don't run `gem update octopress --pre`. Then give this another try to see if you still  get the error.

**Comment by suchja** [comment]
@imathis Such a quick commit. Thanks! Unfortunately only the error message changed. I now get `octopress 3.0.12.pre.1 | Error:  "\xC3" on US-ASCII`. Do you need any other information from my setup?

By every means I don't understand this. When looking into `env` I see `LANG=en_US.utf-8`. Sublime, my editor, shows, that I'm saving my file in `utf-8`.

Not sure whether it is related, but I'm wondering whether the `locale: de_DE` entry in my `_config.yml` has any impact on this. I'm not sure what it is for, but it was used in the theme I'm using. So I changed it from `en_US` to `de_DE`. Tried it with the old setting without any impact, but you never know.

**Comment by suchja** [comment]
Finally! I figured out that it is not an issue with Octopress. I'm running it inside a docker container. There the settings for localisation were not properly set. 
Running the command `locale` inside the container showed that everything was set to "Posix". After setting `-e "LANG=C.UTF-8"` on `docker run`, everything works great.

Thanks for your support!

**Comment by suchja** [comment]
By the way. Keep in mind that on many docker images `en_US.UTF-8` is not available. When using debian as base distribution only `C.UTF-8` will be available.
