### ISSUE TITLE
strange gh-pages deploy

### ISSUE THREAD

**Issue by romanman** [octopress/octopress#132]
I am getting this bad deploy : 
http://ether-camp.github.io/ethereumj.io/

even if you look at the branch it is all set good

https://github.com/ether-camp/ethereumj.io/tree/gh-pages

What can be the reason ?

P.S. I have good deploy in other repository and the same code
than switched to a new one , and got that.

Thanks in advance.

@imathis

**Comment by plttn** [comment]
It looks to me like you've misconfigured your site URL in the deploy
settings (or possibly config.yml). Your site is running on the subdomain
ethereumj.io/, but all your stylesheet references are looking at the main
domain.

**Comment by romanman** [comment]
@plttn : what is the correct way to set it , please

**Comment by plttn** [comment]
I haven't ported my site over to 3.0 yet (I know I should, but it'll be a ordeal), but it should be setting your `site:` variable in `_config.yml` to http://ether-camp.github.io/ethereumj.io/, as I'm guessing it's currently http://ether-camp.github.io/.

**Comment by romanman** [comment]
yep `root: /ethereumj.io` in `_config.yaml` solved

**Comment by imathis** [comment]
Thanks for the assist @plttn!

**Comment by romanman** [comment]
@imathis FYI: some of the aspects 
didn't passed the subdomain config
maybe it's a theme problem (not sure)

http://i.imgur.com/WbHSYwQ.png
