### ISSUE TITLE
Error with octopress deploy which has appeared out of thin air

### ISSUE THREAD

**Issue by damianesteban** [octopress/octopress#146]
Last night I ran `octopress deploy` several times with no issue at all.

Just now I tried to run it and I received the following error:

`octopress 3.0.12.pre.1 | Error:  undefined local variable or method `options' for Octopress::Deploy:Module`

Any thoughts on what might be causing this?

**Comment by bg-scro** [comment]
That just happened to me. Realized I was trying to run the command from a subfolder. When I cd'd back to the root folder for the site, it worked fine.

**Comment by phatblat** [comment]
I kept getting this error on my iMac, but deploying from my MacBook worked just fine. Then I realized that I had generated the `_deploy.yml` on the MacBook, but it's ignored and didn't sync over to the other Mac. Doh! :dizzy_face:
