### ISSUE TITLE
Jekyll 3.0

### ISSUE THREAD

**Issue by drallgood** [octopress/octopress#160]
Hey.

Has anyone tried to use Octopress 3 with Jekyll 3?
I'm running into a few issues (namely, that Jekyll:Post doesn't exist anymore which kills the multilingual plugin)

**Comment by t2d** [comment]
Running into the same problem.

```
# jekyll build --verbose
  Logging at level: debug
Configuration file: /home/t/systemli/systemli-website/_config.yml
         Requiring: /home/t/systemli/systemli-website/src/_plugins/sitemap_generator.rb
         Requiring: octopress-paginate
         Requiring: octopress-multilingual
jekyll 3.1.2 | Error:  undefined method `template' for class `Jekyll::Post'
```

**Comment by LovesTha** [comment]
Commit: https://github.com/octopress/octopress/commit/317fd53423733199bf7b5760a85198352917f83a implies that Jekyll 3.0 is meant to work. So it sounds like you have found a legitimate bug.
