### ISSUE TITLE
Including an image in Octopress 3

### ISSUE THREAD

**Issue by resurrexit** [octopress/octopress#174]
I've been having difficulty including a picture in a post using Octopress 3. I've looked into some of the available plugins, and they are all written for Octopress 2. I've also tried using Liquid tags, a la
`{% img {{root_url}} /images/image.png 'alt' %}`, and other variations like linking to the diagram directly.

I have not been able to embed an image in a post using Octopress 3 once. Any help would be much appreciated.

**Comment by plttn** [comment]
Something like `{% img right /assets/images/travis-ci1.png Where to put the key. %}` should work.

**Comment by resurrexit** [comment]
That worked, thanks! I'm not sure why the path you described worked. I tried something like
`{% img left /source/images/image.png 'diagram' %}`, and _that_ didn't work. Does it have to be the path you wrote, or did I just type something wrong?

**Comment by plttn** [comment]
It shouldn't need to be that path, you might have just mistyped something.

**Comment by resurrexit** [comment]
That is definitely the dumbest thing I've done all day. Thanks! (and I've discovered I can't type)
