### ISSUE TITLE
Known octopress 3 themes

### ISSUE THREAD

**Issue by deg0nz** [octopress/octopress#176]
Hi,
are there any known themes for octopress 3? Any 3rd party themes or old migrated themes?
If I'm googling for this, it seems that all the world is still using octopress 2 (like myself).

I'd like to start using octopress 3 in the near future.

EDIT:
Oh, I just tried an octopress 3 installation.. is it possible to just use any jekyll theme?

**Comment by SpacyRicochet** [comment]
Hey @deg0nz, you probably already figured it out. But still, here's an answer;

Yeah, Octopress 3 is no longer a separate thing from Jekyll. Instead, it works as an additional utility framework around Jekyll, which add extra convience commands.

That means you just create a Jekyll site, with a Jekyll theme and when you want to create and publish drafts and posts easier, you use Octopress 3 for that.

**Comment by deg0nz** [comment]
Alright. This issue is a year old now.. I'm gonna close this.

Thanks for your answer @SpacyRicochet!
