### ISSUE TITLE
The Road to 3.0

### ISSUE THREAD

**Issue by parkr** [octopress/octopress#55]
In order to release 3.0, we have some work ahead of us:

- [ ] `jekyll-paginate` needs to be reworked per https://github.com/octopress/ink/pull/23
- [x] Write `octopress integrate`
- [x] Write `octopress isolate`
- [x] `image` tag plugin
- [x] `pull_quote` tag plugin
- [x] `video` tag plugin
- [ ] Documentation!

Anything else, @imathis? If we can get a comprehensive list here, then we can move forward more swiftly. Async.

**Comment by imathis** [comment]
@VirusKA Yes. I plan to work on a guide once I've finished the first new theme. I just posted a more lengthy comment on migration [here](https://github.com/octopress/octopress/issues/66#issuecomment-68508823)

**Comment by imathis** [comment]
Update: I'm currently working on the new documentation site and things are coming together smoothly. One of the cool things I'm doing with the new Octopress is having each plugin be separate including their documentation. I've built a system that allows me to generate a website which sucks in the documentation from each plugin. The doc site is pretty barebones right now (no css even), but you can browse the documentation for lots of plugins. 

To do that clone this repo, cd into `site` and run `bundle` then `bundle exec jekyll server` That should spin up a site where you can preview the documentation. At this point most plugins are simply adding their Readme and Changelog files.

Anyway, it's cool.

**Comment by imathis** [comment]
Oh and one more thing. If you're curious what "releasing 3.0" means, [Here's a list of all the plugins](https://github.com/octopress/octopress/blob/master/site/_data/_plugins.yml) that will be documented on the new site.

Each of these plugins are fully documented, tested, and feature complete aside from the Genesis theme (which is a work in progress) and Octopress Ink (which is done, but needs more documentation).

**Comment by imathis** [comment]
In the past couple of days I've released:
- octopress-quote-tag
- octopress-pullquote-tag
- octopress-image-tag
- octopress-video-tag

Each with tests and documentation. The documentation site is coming along (content-wise) and I think the last thing I have to do is finish that up and get the Genesis theme into a state where people might want to actually use it.

Things are looking good! I'm excited.

**Comment by parkr** [comment]
Piecemeal plugins, i.e. only-if-you-want-them optional? :smile:

**Comment by imathis** [comment]
Yep. People who have Octopress 2.0 sites will be able to get everything they need during the switch, but they'll have to add a lot to their gemfile—If they used that stuff. I'm eager to dispel the notion that Octopress is a different community from Jekyll. Making sure these work independently is an important part of that.

**Comment by parkr** [comment]
You are so awesome. :clap: :clap: :clap: :clap: :clap: :clap: :clap:

**Comment by imathis** [comment]
Alrighty. I've updated every single Octopress plugin. They now all have documentation, test and are automatically integrated into the new work-in-progress Octopress site. Other than some better documentation for Octopress Ink, the only thing I have left is to finish the Genesis theme.

Once those are done. I'll finish up the site, migrating whatever pages still make sense to keep from the old site. And then I'll be ready to replace imathis/octopress with this and do the release. Yay!

**Comment by parkr** [comment]
Hot damn!

**Comment by imathis** [comment]
I decided to count. There are 28 gems that are a part of this release. O.o. Exciting stuff.

@parkr you mentioned some headway on the pagination stuff. Any luck with that so far?

**Comment by parkr** [comment]
> @parkr you mentioned some headway on the pagination stuff. Any luck with that so far?

I had made some headway but didn't like it. The struggle is the user interface – what is the best way to set this up? I reworked it to look like this:

![screen shot 2015-01-11 at 8 08 15 pm](https://cloud.githubusercontent.com/assets/237985/5698883/a3548314-99cd-11e4-92b4-c125b2ad8db4.png)

**Comment by imathis** [comment]
Honestly, that looks really easy to configure. I'm guessing the default template for posts wouldn't be `_posts/pager.html`. Posts being different by default is maybe the only thing that may confuse users.

**Comment by parkr** [comment]
I was thinking about using `_templates` or some other "reserved" folder but now that there are custom collections, this isn't super possible. Maybe `_layouts/pager.html` would be better?

**Comment by imathis** [comment]
I know custom collections are a thing, but _includes, _layouts, _data, and _posts can't be reused for something else right now can they? It's probably too late to reserve other folder names, but it seems like as long as you can configure it, you should be okay with _templates. If not though, I think _layouts/pager.html works fine.

**Comment by parkr** [comment]
> It's probably too late to reserve other folder names

That's how I feel right now. The more configuration we add, the harder it becomes to use so I'd rather not have yet another reserved folder name.

> I think _layouts/pager.html works fine.

Another option is `_layouts/templates/pager.html`.

**Comment by imathis** [comment]
> Another option is _layouts/templates/pager.html.

Of the suggestions, this is probably the least likely to interfere with an existing setup :+1:

**Comment by imathis** [comment]
It makes me wonder if I should change the way Octopress scaffolding works and use the same folder. Though, It's not really a layout per se.

**Comment by daveheitzman** [comment]
say I wanted to whip up a quick site right now.. 
so I installed the Octopress gem, made a new site. 
But I'm a bit lost - what would i do in place of the old octopress generate command? 

Thanks for all your work on this. Can't wait to see the Genesis theme.

**Comment by justinrummel** [comment]
They are jekyll commands now.  to test via http://localhost:4000 you only need ```jekyll s```.  If you are going to use the deploy option, do ```jekyll b; octopress deploy```.

https://www.justinrummel.com/migrating-from-octopress-2-to-octopress-3/

**Comment by daveheitzman** [comment]
Okay, that helps. Would there be any plans to still support octopress commands, even if it just translated them directly to underlying jekyll commands?

**Comment by sondr3** [comment]
Personally I think they should be a 2.0 feature seeing as 3.0 isn't a replacement for Jekyll but something that goes along with it, having Octopress do the same commands that Jekyll is doing already seems a bit weird to me, KISS and all that.

**Comment by imathis** [comment]
I'm not planning to offer Octopress alternative to Jekyll command unless there is useful way I can augment the command. For example. `octopress new .` == `jekyll new .; octopress init .`. So far that's the only command I've seen the utility in coopting, and it directly references the Jekyll command, passing along options and all.

**Comment by daveheitzman** [comment]
Okay, so what I'm getting is: learn Jekyll first, then use Octopress for extra features, like themes.

**Comment by imathis** [comment]
@daveheitzman Right on. Octopress is shifting away from being a thing that lives between you and Jekyll and towards being a cohesive ecosystem of plugins and UX enhancements for Jekyll.

**Comment by daveheitzman** [comment]
Excellent.

**Comment by alec-c4** [comment]
Hi, Brandon, guys. 
I have some questions, hope you can help ;)
- do you have plans to integrate disqus comments to Octopress 3?
- how to enable code highlighter with line numbers? I've installed codefence but still have the same look :(

**Comment by imathis** [comment]
If you're running your blog on a previous version of Octopress, you'll probably want to remove "@import "partials/syntax";" from your `sass/_partials.scss` file, then install [octopress-solarized](https://github.com/octopress/solarized). That should do it for you.

**Comment by imathis** [comment]
@alec-c4 Oh, I forgot to answer your other question. On Disqus, I'd rather build a system that makes it easy to add whatever you want to your site. As I'm finishing up the new theme, I'll see how hard it is to manually integrate. If it's a pain, I'll probably build something.

**Comment by alec-c4** [comment]
hmmm, it looks like there are a lot of problems:
1 - I've reinstall Octopress with default config
on most of shel commands i see warning:
```
 octopress new alec-c4.com
/Users/alec/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/liquid-2.6.1/lib/liquid/htmltags.rb:43: warning: duplicated key at line 46 ignored: "index0"
New jekyll site installed in /Users/alec/Documents/Blog/alec-c4.com.
Added Octopress scaffold:
 + _templates/
 +   draft
 +   page
 +   post
```

as i understand - there are problems with liquid gem

2 - i've tried to install octopress-solarized theme. My gemfile looks like

```
source "https://rubygems.org"

gem 'octopress', '~> 3.0.0.rc.28'
gem 'rake'
gem 'octopress-deploy'
gem 'aws-sdk'

gem 'octopress-codefence'
gem 'octopress-linkblog'
gem 'octopress-ink'
gem 'octopress-solarized'
```

Also i've tried to wrap octopress-* gems with group :jekyll_plugins'.

My config looks like

```
# Site settings
title: Always Sleepy
email: my@email
description: > # this means to ignore newlines until "baseurl:"
  Notes of great and wonderful me :)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alec-c4.com" # the base hostname & protocol for your site
twitter_username: alec_c4
github_username: alec-c4

# Build settings
markdown: kramdown

gems:
  - octopress-codefence
  - octopress-linkblog
  - octopress-ink
  - octopress-solarized

exclude: [.bundle, bin, vendor]
```

I've added example code from codefence ready and it slit looks like http://take.ms/hqql3

You know - it looks like i have problems with gems loading. The same - with the themes.

**Comment by alec-c4** [comment]
And - i have no file sass/_partials.scss :(

**Comment by imathis** [comment]
@alec-c4 It looks like you probably haven't followed the installation instructions for [octopress-solarized](https://github.com/octopress/solarized). You'll want to put `{% css_asset_tag %}` in your site's header to add the stylesheets. If you have further trouble, please file an issue at the octopress-solarized repository and I'll help you there.

**Comment by dmayer** [comment]
If I were to create a new site right now, should I go with 2 or 3? Any idea when the first release of 3 will be?

Thanks for your great work!

**Comment by davidized** [comment]
I would say go with 3, I created a new site a few weeks ago using gems from 3 and have had no major problems.

**Comment by parkr** [comment]
3 has been released :)
