### ISSUE TITLE
new page folder/ generates index.html

### ISSUE THREAD

**Issue by justinrummel** [octopress/octopress#71]
when performing a ```octopress new page test/``` to generate a subdirectory in your site (e.g. http://mysite.com/test/), octopress is generating the "test" folder, but inside is a index.html file with markdown attributes. I believe it is supposed to be index.md.

**Comment by mjohnq3** [comment]
The default for Pages is html but this can be changed in your _config.yml file per: https://github.com/octopress/octopress/blob/master/assets/docs/index.md#configuration

**Comment by imathis** [comment]
Have you configured new pages to default to `md`? If you want it to be markdown add `page_ext: md`
