### ISSUE TITLE
paginate and post content

### ISSUE THREAD

**Issue by justinrummel** [octopress/octopress#72]
I'm trying to get the main index homepage to look like my [Octopress 2 site](https://www.justinrummel.com) displaying the last five articles and all of their content vs. a page that has a link to each article as seen attached.

I'm assuming it's just a setting in the _config.yml, I just can't find it.  Current source is available on my [octo3 repo](https://github.com/justinrummel/jr.com-octo3/tree/master/www).

![image 2015-01-08 at 7 40 15 pm](https://cloud.githubusercontent.com/assets/466605/5674517/b9572870-9779-11e4-90f0-3a86bf4d29b1.png)

**Comment by mjohnq3** [comment]
One way to do it is; instead of using :
```
{% for post in site.posts %}
```
in your index.html, you would use:
```
{% for post in paginator.posts %}
```
Then in _config.yml add:
```
paginate: 5
```
You can see this used in my index.html here: https://github.com/mjohnq3/jekyll-writer/blob/master/index.html

To display the full content of each post, use:
```
{{ post.content }}
```
at an appropriate place in index.html.
