### ISSUE TITLE
Viewing drafts

### ISSUE THREAD

**Issue by IanWhitney** [octopress/octopress#76]
I like the ability to create drafts, but I do not see how to preview them. They don't show up when I do `jekyll serve` and the isolate command can't find a draft.

So, am I just using drafts wrong or is there a command that I'm missing?

**Comment by mjohnq3** [comment]
Use jekyll serve --drafts

http://jekyllrb.com/docs/drafts/

**Comment by imathis** [comment]
Yep, that should do it. Thanks for the help @mjohnq3!
