### ISSUE TITLE
Drafts _template workflow

### ISSUE THREAD

**Issue by justinrummel** [octopress/octopress#78]
When creating a draft via ```octopress new draft "title goes here"``` I'm getting the following template layout information: 

``` bash
---
layout: post
title: "Title Goes Here"
---
```

When I'm ready to publish thus performing ```octopress publish _drafts/title-goes-here.markdown``` I would expect to get the _template/post header framework applied, but instead there is only: 

``` bash
---
layout: post
title: "Title Goes Here"
date: 2015-01-15T10:04:43-05:00
---
```
I'm not sure if the answer is to create a new _template/draft, use the existing _template/post, or when publishing apply the _template/post.

**Comment by imathis** [comment]
This is a good question. Only the `new` command use the template. So `new page`, `new post`, `new draft` all have a template. The publish command preserves the YAML front-matter from the draft so any changes you make to it will end up in the post. I could add a `--template` option to the publish, but I think it's better to expect users to edit their files and keep them in tact.

If you want to use your post template for drafts you can do `octopress new draft --template post` or change the draft to match your post template.

**Comment by justinrummel** [comment]
I would like "if _template/draft exists", then use that template.  It helps me remember what items need update (like tags, publish, comments, etc).  If it doesn't exist do the current behavior of just layout and title. I would then just ```cp _template/post _template/draft``` so the template file does exist in my environment. 

However, including a ```--template post``` is a good alternative.  I'll just have to remember to include those flags when creating a draft.

**Comment by imathis** [comment]
I'm not sure I entire understand what you want. But I've just pushed a new update that may help. You can now set `draft_template: post` in your `_config.yml` and you won't need a `_templates/draft`file since it will use `_templates/post` as the template. Then you won't have to pass the `--template` flag.

**Comment by imathis** [comment]
I don't know what the deal is with the copy of your site that I have here, but it's not working for me. Would you mind sending me another?

**Comment by imathis** [comment]
Oops, wrong issue.

**Comment by justinrummel** [comment]
PERFECT! I didn't think of that solution and it returns exactly what I was looking for!

**Comment by imathis** [comment]
Excellent. I'm glad to hear it.
