### ISSUE TITLE
htmltags.rb:43: warning: duplicated key at line 46 ignored: "index0"

### ISSUE THREAD

**Issue by sammcj** [octopress/octopress#82]
```
 % gem install octopress --pre
 % octopress
/Users/samm/.rvm/gems/ruby-2.2.0/gems/liquid-2.6.1/lib/liquid/htmltags.rb:43: warning: duplicated key at line 46 ignored: "index0"
```

```
  ruby:
    interpreter:  "ruby"
    version:      "2.2.0p0"
    date:         "2014-12-25"
    platform:     "x86_64-darwin14"
    patchlevel:   "2014-12-25 revision 49005"
    full_version: "ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]"
```

**Comment by parkr** [comment]
Fixed by https://github.com/Shopify/liquid/pull/503 . Just not released.

**Comment by imathis** [comment]
This appears to be an issue with Liquid. Perhaps it isn't happy with Ruby 2.2.0. Try the same in `gem install liquid` and see what happens.

**Comment by imathis** [comment]
Oops, hadn't seen your post @Parkr. Thanks!

**Comment by arthurnn** [comment]
@parkr FYI, we just released https://rubygems.org/gems/liquid/versions/3.0.1 and https://rubygems.org/gems/liquid/versions/2.6.2 with the appropriate fix for this issue.

**Comment by parkr** [comment]
@arthurnn :heartbeat:

**Comment by rjurney** [comment]
Seeing this issue with liquid 3.0.6.
