### ISSUE TITLE
octopress deploy issue

### ISSUE THREAD

**Issue by change2hao** [octopress/octopress#83]
Hi,imathis. I installed octopress3.0 step by step following your readme today. Unfortunately,when I exec  'octopress deploy init git' , the console show 'octopress 3.0.0.rc.28 | Error:  undefined method `sub!' for nil:NilClass' , when I change to 'octopress deploy init s3', it works well. I have installed git and I work on Yosemite.

**Comment by mjohnq3** [comment]
I get the same error on Windows 8.1 with Ruby 2.0.0p481. Initializing git did previously work correctly.

**Comment by imathis** [comment]
I'm taking a look. Thanks for the report.

**Comment by imathis** [comment]
I just released version 1.0.4 of octopress-deploy. I failed to mention in the Readme that the `--url` was required for the `init git` command. Now when you run the command without typing the url, it will print out the command usage asking for an option.
