### ISSUE TITLE
[3.0.0.rc.30] Is the new octopress 2.2.0 compatible?

### ISSUE THREAD

**Issue by keltia** [octopress/octopress#86]
(moved from imathis/octopress)

OS X 10.10.1, clang 3.5, ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14].

Hello, 

Everytime I run octopress, I get this error message:

    /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/safe_yaml-1.0.3/lib/safe_yaml/load.rb:43:in `<module:SafeYAML>': undefined method `tagged_classes' for Psych:Module (NoMethodError)
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/safe_yaml-1.0.3/lib/safe_yaml/load.rb:26:in `<top (required)>'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.4.0/lib/jekyll.rb:26:in `<top (required)>'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/octopress-3.0.0.rc.30/lib/octopress/command.rb:1:in `<top (required)>'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/octopress-3.0.0.rc.30/lib/octopress.rb:5:in `<module:Octopress>'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/octopress-3.0.0.rc.30/lib/octopress.rb:4:in `<top (required)>'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/octopress-3.0.0.rc.30/bin/octopress:6:in `<top (required)>'
	from /Users/roberto/.rbenv/versions/2.2.0/bin/octopress:23:in `load'
	from /Users/roberto/.rbenv/versions/2.2.0/bin/octopress:23:in `<main>'

does that mean that it can't be run under 2.2.0?

**Comment by imathis** [comment]
I've just installed 2.2.0 under rbenv on OS X 10.10 and the tests pass without issue (aside from some warnings due to a bug in liquid). Can you give me some more details about your environment? What OS are you running? I'm going to add 2.2.0 to the travis.yml and see how travis fares.

**Comment by keltia** [comment]
OS X 10.10.1 (see above).

`gem env`gives this:

    296 [17:13] roberto@roberto-aw:Perso/Sites> gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.5
  - RUBY VERSION: 2.2.0 (2014-12-25 patchlevel 0) [x86_64-darwin14]
  - INSTALLATION DIRECTORY: /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0
  - RUBY EXECUTABLE: /Users/roberto/.rbenv/versions/2.2.0/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/roberto/.rbenv/versions/2.2.0/bin
  - SPEC CACHE DIRECTORY: /Users/roberto/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/roberto/.rbenv/versions/2.2.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-14
  - GEM PATHS:
     - /Users/roberto/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0
     - /Users/roberto/.gem/ruby/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :benchmark => false
     - :sources => ["http://gems.rubyforge.org/", "http://gems.github.com", "http://gemcutter.org"]
  - REMOTE SOURCES:
     - http://gems.rubyforge.org/
     - http://gems.github.com
     - http://gemcutter.org
  - SHELL PATH:
     - /Users/roberto/.rbenv/versions/2.2.0/bin
     - /Users/roberto/.rbenv/libexec
     - /Users/roberto/.rbenv/plugins/ruby-build/bin
     - /Users/roberto/.rbenv/plugins/rbenv-macruby/bin
     - /Users/roberto/.rbenv/bin
     - /usr/local/bin
     - /opt/local/bin
     - /opt/local/sbin
     - /Users/roberto/.rbenv/shims
     - /usr/texbin
     - /usr/local/bin
     - /usr/local/sbin
     - /opt/local/bin
     - /Users/roberto/shell
     - /opt/local/sbin
     - /usr/X11R6/bin
     - /Users/roberto/.rbenv/bin
     - /usr/local/bin
     - /opt/local/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /opt/X11/bin
     - /usr/local/MacGPG2/bin
     - .
     - /Users/roberto/Shell
     - .

**Comment by imathis** [comment]
With a fresh install of 2.2.0, my `gem env` is nearly identical to yours, the only differences being shell paths and sources. I don't see why you should be having these errors. Are you running `bundle exec` before running octopress commands?

**Comment by imathis** [comment]
It looks like the [tests pass](https://travis-ci.org/octopress/octopress/jobs/47665858) on Travis for 2.2.0. And they pass for me on OS X 10.10.1. I hate that I can't give you some direction, but it looks like this is a local issue affecting your setup only so I think I'm going to close this issue. If you find anything that can resolve it, please let me know as it may be helpful to others.

**Comment by keltia** [comment]
According to Brandon Mathis:
> It looks like the [tests pass](https://travis-ci.org/octopress/octopress/jobs/47665858) on Travis for 2.2.0. And they pass for me on OS X 10.10.1. I hate that I can't give you some direction, but it looks like this is a local issue affecting your setup only so I think I'm going to close this issue. If you find anything that can resolve it, please let me know as it may be helpful to others.

No worry, thanks.  I'll check further on my setup.

-- 
Ollivier ROBERT -=- FreeBSD: The Power to Serve! -=- roberto@keltia.net
In memoriam to Ondine, our 2nd child: http://ondine.keltia.net/

**Comment by parkr** [comment]
@keltia Psych problems are usually fixed by re-installing Ruby.

**Comment by deluan** [comment]
Just for the record, I had this problem with a newly installed Ruby 2.2.0 instance and the solution for me was running `bundle update` after `bundle install`. 

This is the post that helped me: http://stackoverflow.com/questions/29245100/github-pages-error-running-jekyll-locally

**Comment by imathis** [comment]
Interesting. Thanks for the update @deluan
