### ISSUE TITLE
Excerpts?

### ISSUE THREAD

**Issue by drallgood** [octopress/octopress#87]
Octopress 2 had a filter that allowed you to create/use excerpts. 
Is there a replacement for it in 3.0?

**Comment by justinrummel** [comment]
Jekyll now has a built-in Excerpt capabilities listed on http://jekyllrb.com/docs/posts/ by defining your excerpt_separator in your _config.yml.

**Comment by drallgood** [comment]
Oh.. I missed that somehow. 

Thanks!
