### ISSUE TITLE
Error reading file and Invalid argument error when running Rake Generate

### ISSUE THREAD

**Issue by Summonee** [octopress/octopress#88]
Since yesterday, I've been getting this error when running Rake Generate:

> Error reading file C:/Users/Jackson/Dropbox/ValiantOctoGhost/source/C:/Users/Jackson/Dropbox/ValiantOctoGhost/public/index.html: Invalid argument - /Users/Jackson/Dropbox/ValiantOctoGhost/source/C:/Users/Jackson/Dropbox/ValiantOctoGhost/public/index.html
Error reading file C:/Users/Jackson/Dropbox/ValiantOctoGhost/source/C:/Users/Jackson/Dropbox/ValiantOctoGhost/public/blog/index.html: Invalid argument - /Users/Jackson/Dropbox/ValiantOctoGhost/source/C:/Users/Jackson/Dropbox/ValiantOctoGhost/public/blog/index.html
jekyll 2.5.3 | Error:  undefined method `encode!' for nil:NilClass

I have no clue exactly what to do. I've tried deleting the files, restoring them and nothing works. Please help, you're my only hope!

**Comment by imathis** [comment]
Are you using the latest version of Octopress at [imathis/octopress](https://github.com/imathis/occtopress) or are you using 3.0? What did you change yesterday? Are you using Bundler? I need some more information.

**Comment by Summonee** [comment]
Thank you for replying. I am using 3.0 and I have been for a long time. I didn't change anything, other than write a few posts, and Bundler works fine. I hope this helps.

And a side note, thank you for this awesome thing you've created.

**Comment by imathis** [comment]
Have you tried just running `bundle exec jekyll build --trace` to see what's going wrong?

**Comment by Summonee** [comment]
Here is the output

>DL is deprecated, please use Fiddle
Configuration file: C:/Users/Jackson/Dropbox/ValiantOctoGhost/_config.yml
            Source: source
       Destination: public
      Generating...
Error reading file C:/Users/Jackson/Dropbox/ValiantOctoGhost/source/C:/Users/Jackson/Dropbox/ValiantOctoGhost/public/index.html: Invalid argument - /Users/Jackson/Dropbox/ValiantOctoGhost/source/C:/Users/Jackson/Dropbox/ValiantOctoGhost/public/index.html
Error reading file C:/Users/Jackson/Dropbox/ValiantOctoGhost/source/C:/Users/Jackson/Dropbox/ValiantOctoGhost/public/blog/index.html: Invalid argument - /Users/Jackson/Dropbox/ValiantOctoGhost/source/C:/Users/Jackson/Dropbox/ValiantOctoGhost/public/blog/index.html
C:/ruby200/lib/ruby/gems/2.0.0/gems/octopress-codefence-1.5.1/lib/octopress-codefence.rb:30:in `render': undefined method `encode!' for nil:NilClass (NoMethodError)
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/octopress-codefence-1.5.1/lib/octopress-codefence.rb:9:in `pre_render'
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/octopress-hooks-2.2.3/lib/octopress-hooks.rb:249:in `block in pre_render'
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/octopress-hooks-2.2.3/lib/octopress-hooks.rb:248:in `each'
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/octopress-hooks-2.2.3/lib/octopress-hooks.rb:248:in `pre_render'
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/octopress-hooks-2.2.3/lib/octopress-hooks.rb:222:in `do_layout'
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/page.rb:122:in `render'
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:298:in `block in render'
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `each'
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `render'
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/octopress-hooks-2.2.3/lib/octopress-hooks.rb:138:in `render'
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:51:in `process'
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
        from C:/ruby200/bin/jekyll:23:in `load'
        from C:/ruby200/bin/jekyll:23:in `<main>'

Which makes me think there's more than one problem here.

**Comment by plttn** [comment]
I can't remember the solve to this off the top of my head (isn't knowing
you've seen this exact issue before and being unable to remember where
wonderful?), but if you look at the paths it's calling, it's going to your
sourcedir, and then appending another path after that, causing jekyll to
freak out.

**Comment by Summonee** [comment]
That was one of the first things I realised, and I have no clue how to fix it. Seriously, I can see what I would have to do and no clue how to do it.

**Comment by imathis** [comment]
Are you keeping your source checked into git? If this just started recently and you don't think you've changed anything that would cause this kind of freak-out, you can always walk back through your git commits and see which change breaks things. That's at least a start. Another option is to move all your posts and pages and try adding them back one at a time until it breaks.

**Comment by plttn** [comment]
@imathis there were references to a similar issue over on jekyll/jekyll#3084. but I can't confirm whether that was fixed or not in 2.5.3.

I can run some tests on my Windows machine in a bit using 3.0.

(also in 3.0 you should be using `jekyll build`, not `bundle exec rake build`)

**Comment by Summonee** [comment]
It seems it was indeed a few recent posts I had written messing with it (Somehow). Just to be safe, I rolled back to the last known working commit.

If I figure out why the posts were messing with it, Ill post it here.

Thank you all for your help.

**Comment by imathis** [comment]
Excellent. I hope it's a simple fix for you.

**Comment by Summonee** [comment]
Well in fact, it turns out that any new post I write after the last good ones gives me the same error again! Please help me again?

Also, I ran Jekyll Build, and heres what I got:

> λ jekyll build                                                                                                                                      
WARN: Unresolved specs during Gem::Specification.reset:                                                                                             
      pygments.rb (~> 0.6.0)                                                                                                                        
      redcarpet (~> 3.1)                                                                                                                            
      jekyll-watch (~> 1.1)                                                                                                                         
      classifier-reborn (~> 2.0)                                                                                                                    
WARN: Clearing out unresolved specs.                                                                                                                
Please report a bug if this causes problems.                                                                                                        
C:/ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:21:in `block in <top (required)>': cannot load such file -- jekyll/version (LoadError)  
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:18:in `program'                                                   
        from C:/ruby200/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'                                                   
        from C:/ruby200/bin/jekyll:23:in `load'                                                                                                     
        from C:/ruby200/bin/jekyll:23:in `<main>'

**Comment by imathis** [comment]
Try deleting your Gemfile.lock and running `bundle install`. It seems like there's something wrong with your installed gems.

**Comment by plttn** [comment]
If that doesn't work, remove your Gemfile.lock again, run `gem uninstall jekyll`, and then `gem install jekyll -v 2.4.0`

It's possible that they still haven't fixed the Windows issues.

**Comment by Summonee** [comment]
Well, it appears it was indeed a Jekyll error. Downgrading to 2.4.0 seems to have fixed the issue. I wrote a few posts just to check, and it all seems to work. Hooray!

**Comment by pinalbhatt** [comment]
Deleting Gemfile.lock helped me to resolve this issue .
