### ISSUE TITLE
Octopress Compability with Jekyll v3.0.0.beta1?

### ISSUE THREAD

**Issue by gntech** [octopress/octopress#89]
I tried to use some of the octopress gem plugins together with Jekyll v3.0.0.beta1 but didnt manage to run. Are they not compatible at the moment or did I perhaps do something wrong? (Not impossible at all, being quite new in the rubygems world :) )

The plugins was octopress-image-tag and octopress-filters

**Comment by imathis** [comment]
@gntech Thanks for the post. Octopress isn't yet compatible with Jekyll 3. There are a lot of things that are changing internally in Jekyll, and I want to wait until it is close to release before I rebuild things on it.

**Comment by gntech** [comment]
Okay, thanks for the info!
