### ISSUE TITLE
Cloud9 push Octopress3 to Heroku

### ISSUE THREAD

**Issue by schipperius** [octopress/octopress#92]
I get the following error when trying to push Octopress3 from Cloud9 to Heroku, and I am not really sure where to ask for help as I have been unable to troubleshoot the error.
 
$ git push heroku master
results in the following:

remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Ruby app detected
remote: -----> Compiling Ruby
remote: sh: 7: Syntax error: EOF in backquote substitution
remote:  !
remote:  !     There was an error parsing your Gemfile, we cannot continue
remote:  !     There was a LoadError while loading octopress.gemspec:
remote:  !     no such file to load -- octopress/version from
remote:  !     /tmp/build_56e528cef60c8c54a7f78e12f5d520f2/octopress.gemspec:4:in `<main>'
remote:  !     
remote:  !     Does it try to require a relative path? That's been removed in Ruby 1.9.
remote:  !
remote: 
remote:  !     Push rejected, failed to compile Ruby app
remote: 
remote: Verifying deploy...
remote: 
remote: !       Push rejected to nature-of-things-1.
remote: 

Thanks in advance,
Mark

**Comment by imathis** [comment]
I'm honestly not sure what this is about. I don't believe I'm doing anything uncommon when requiring the version. @parkr do you have any idea?

**Comment by parkr** [comment]
@schipperius Do you have a link to your site? This tells me to look in your `Gemfile`:

```
remote: sh: 7: Syntax error: EOF in backquote substitution
remote: !
remote: ! There was an error parsing your Gemfile, we cannot continue
remote: ! There was a LoadError while loading octopress.gemspec:
remote: ! no such file to load -- octopress/version from
remote: ! /tmp/build_56e528cef60c8c54a7f78e12f5d520f2/octopress.gemspec:4:in `'
remote: !
```

Make sure you have not just cloned github.com/octopress/octopress.git – you need to do `octopress new` (or is it init?).

**Comment by schipperius** [comment]
Thanks for responding so quickly. I deleted and rebuilt all the pieces I could related to the Gemfile, gems, gemspec, etc. but have arrived after many hours to the same error:

```There was a LoadError while loading octopress.gemspec: 
cannot load such file -- octopress/version from
  /home/ubuntu/workspace/octopress.gemspec:4:in `<main>'

Does it try to require a relative path? That's been removed in Ruby 1.9.```

The site is: https://nature-of-things-1-schipperius.c9.io/ and https://github.com/schipperius/nature-of-things-1.

I would describe myself an 'advanced beginner', so it may be more economical if I simply start over as it's quite possible my comprehension is quite low, lol. But of course, any help would be appreciated!

**Comment by plttn** [comment]
@schipperius I haven't really worked with Octopress 3.0 yet, but is there a reason why you're using gemspec vs. just adding octopress to your Gemfile? It looks like it has an issue with that `octopress/version` file, which isn't something that should be done on a local install (I think, I'm sure imathis/parkr would know the exact answer to that).

**Comment by schipperius** [comment]
Thanks @plttn, that helped. I removed gemspec file, updated Gemfile and was able to push to heroku with no errors. 

But Heroku open now throws new xdg-open error. Heroku logs didn't seem to shed too much light and online searches did not reveal too much either. So, I thought I would build a new Jekyll site just to see how things might differ... Heroku open creates same error:

~/workspace (master) $ heroku open
Opening nature-of-things-3... xprop:  unable to open display ''
xprop:  unable to open display ''
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'https://nature-of-things-3.herokuapp.com/'
done

I never came across these error messages with a local dev env using OS X, perhaps something funny going on with Cloud9?

**Comment by parkr** [comment]
@schipperius It can't find a browser on your machine.

**Comment by schipperius** [comment]
Well, I couldn't quite figure out what I did so I've started a new site and will follow the development of octopress 3, thanks. This issue can be considered closed.

Mark

**Comment by plttn** [comment]
@schipperius Yeah. Cloud9 doesn't have any browser to open, so `heroku open` will definitely fail. That's not an octopress issue, that's a Cloud9 issue.
