### ISSUE TITLE
Error:  undefined method `require_from_bundler'

### ISSUE THREAD

**Issue by tunnelsup** [octopress/octopress#94]
I am trying to use the opentheme.co Jekyll them and octopress. My installation process is simply like this:

`git clone https://github.com/open-start/opentheme.git`

Then I add the gem to the gemfile:
`gem 'octopress', '~> 3.0.0.rc'`

After doing bundle I can do things like `octopress init` and `octopress -v` but when I try to make a new post I get this error:

    $ octopress new post "test post"
    octopress 3.0.0.rc.34 | Error:  undefined method `require_from_bundler' for Jekyll::PluginManager:Class
    
I believe this is getting stuck in /lib/octopress.rb on line 68 where it reads this:

    Jekyll::PluginManager.require_from_bundler

Perhaps these two things aren't compatible. Any ideas to make it work?

**Comment by justinrummel** [comment]
There is some kind of dependency as I was able build with only a warnings: 

``` bash
WARN: Unresolved specs during Gem::Specification.reset:
      pygments.rb (~> 0.6.0)
      redcarpet (~> 3.1)
WARN: Clearing out unresolved specs.
```

However, once I did a ```sudo bundle clean --force``` I received the same errors as you.  My current Gemfile is at: https://github.com/justinrummel/jr.com-hpstr/blob/master/Gemfile to see if adding one of these gems may help.

**Comment by tunnelsup** [comment]
Great. Your gemfile got me past the error I was hitting. But now I get a different error:

    $ jekyll serve 
    Configuration file: /Users/me/web/jkocto3/_config.yml
                Source: /Users/me/web/jkocto3/
           Destination: /Users/me/web/jkocto3/_site
          Generating... 
      Populating LSI... 
    Rebuilding index... jekyll 2.4.0 | Error:  Zero vectors can not be normalized

**Comment by mebezac** [comment]
Yeah you have jekyll 2.4.0 on your system. `require_from_bundler` wasn't introduced until jekyll 2.5.0, so you just need to update your jekyll version.

**Comment by tunnelsup** [comment]
Thanks. I do believed that solved it! But my master plan isn't going to work because one of my gems 'github-pages' requires Jekyll 2.4.0 and isn't on 2.5.0+ yet. https://github.com/github/pages-gem/issues/121

**Comment by imathis** [comment]
Well darn. Really there's not much I can do about that. Sorry.

**Comment by mebezac** [comment]
@tunnelsup looks like you're using the opentheme. The `github-pages` gem is just to make sure you can push your jekyll code to a repo and have GitHub turn it into a static site for you. 

If you remove that gem, you can then use the new version of Octopress. Then if you want to host your site on GitHub, all you have to do is run `jekyll build` to generate the static site and then push the contents of the `_site` folder to your repo along with a `.nojekyll` file. That's what I do with my blog: https://github.com/mebezac/mebezac.github.io

**Comment by tunnelsup** [comment]
Thanks @mebezac! With your help I was able to finally get octopress3 and opentheme installed together. I'm really excited about this and will be launching a new blog using these method very soon.
